# -*- coding: utf-8 -*-
"""OOP.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mLWErQ20VsdCOfAmR4p-r21ZaKpIcdGi
"""

class Animals:
  def __init__(self,name):
    self.name=name
  def eat (self):
    print(f"{self.name} is eating")
  def sleep(self):
    print(f"{self.name} is sleeping")

class Dog(Animals):
  def bark(self):
    print(f"{self.name} is barking")

class Cat(Animals):
  def meow(self):
    print(f"{self.name} is meowing")

cat = Cat("tom")
dog = Dog("lio")

cat.eat()
cat.sleep()
cat.meow()

dog.eat()
dog.sleep()
dog.bark()